cloud:
  aws:
    s3:
      bucket: lhsbucket98
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: "##################"
      secret-key: "################################"
